# Generated by Django 4.2.7 on 2023-12-04 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=30)),
                ('userlastname', models.CharField(max_length=60)),
                ('date_of_birth', models.DateField()),
            ],
        ),
    ]
