# Generated by Django 4.2.7 on 2023-12-04 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Kalendari',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tarigi', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
