# Generated by Django 4.2.7 on 2023-12-11 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('animal', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='animal',
            name='animal_age',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='animal',
            name='animal_breed',
            field=models.CharField(default='None', max_length=50),
        ),
        migrations.AddField(
            model_name='animal',
            name='animal_kind',
            field=models.CharField(default='None', max_length=50),
        ),
        migrations.AddField(
            model_name='animal',
            name='animal_name',
            field=models.CharField(default='None', max_length=50),
        ),
    ]
